### PR TITLE
Added a bunch of pride flag masks for filters.py

### PR DESCRIPTION
**Pull request by AxoManAxo**

### CODE REVIEW

**Review by dovedevic — CHANGES_REQUESTED** [review]
remove the commits for fun.py and bot.py

**Comment by dovedevic** [comment]
Also maybe it would be nice to just apply all these in one big function, say apply_overlay, where you pass in a filter, and it does the code youve copied pasted.

**Review by dovedevic — CHANGES_REQUESTED** [review]
remove the changes to bot.py and fun.py. May as well update the gay filter and the commie filter to use this.

**Comment by nwunderly** [comment]
Counterpoint, leave the changes but make it so $howlongtill10k returns a negative number.

**Comment by dovedevic** [comment]
Or perhaps how long til 20k

**Review by PineaFan — APPROVED** [review]

**Review by nwunderly — CHANGES_REQUESTED** [review]
Literally every new command added here is missing the `ctx` argument. The `apply_mask` calls within these functions are also missing the context.

**Review by nwunderly — APPROVED** [review]

**Review by dovedevic — APPROVED** [review]

**Pull request merged**
